version: '3.9'

services:
  nginx:
    build: ./TestingProject/nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/home/app/microservice/static
    depends_on:
      - web
    restart: "on-failure"
  web:
    build: . #build the image for the web service from the dockerfile in parent directory
    command: sh -c "gunicorn TestingProject.asgi:app -w 4 -k uvicorn.workers.UvicornWorker && python manage.py collectstatic "

    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
      - static_volume:/home/app/microservice/static
    env_file:
      - .env
    image: testingproject
    
volumes:
  static_volume: