# Generated by Django 3.2.3 on 2021-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('Name', models.CharField(max_length=40)),
                ('Group', models.CharField(max_length=50)),
                ('Salary', models.IntegerField()),
                ('UniqueID', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('Description', models.TextField()),
            ],
        ),
    ]
